### ISSUE TITLE
Error in sdimg

### ISSUE THREAD

**Issue by whileTrueShoaib** [hyugogirubato/pyImagine#3]
The function sdimg is throwing this error 

 raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://inferenceengine.vyro.ai/sdimg

**Comment by hyugogirubato** [comment]
I will check if I also have the error.

**Comment by hyugogirubato** [comment]
I actually forgot parameters for this request, I corrected this problem via the new update. Thanks 💯

**Comment by ashir57** [comment]
nah bro still same here is a full error 


Traceback (most recent call last):
  File "F:\Codes\Python\imaginary\main.py", line 56, in <module>
    vere()
  File "F:\Codes\Python\imaginary\main.py", line 39, in vere
    img_data = imagine.sdimg(        
               ^^^^^^^^^^^^^^        
  File "C:\Users\Ashir\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyimagine\vyroai.py", line 166, in sdimg
    return bytes2png(self._request(  
                     ^^^^^^^^^^^^^^  
  File "C:\Users\Ashir\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyimagine\vyroai.py", line 60, in _request
    r.raise_for_status()
  File "C:\Users\Ashir\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://inferenceengine.vyro.ai/sdimg

**Comment by whileTrueShoaib** [comment]
Thank You, its now working fine  <3
